### ISSUE TITLE
Javascript port

### ISSUE THREAD

**Issue by m-mohr** [rouault/projjson_to_wkt#2]
Just as a fyi: I've created a Javascript port of the Python code at https://github.com/m-mohr/projjson_to_wkt

**Comment by rouault** [comment]
cool, feel free to edit https://github.com/rouault/projjson_to_wkt/blob/master/README.md to point to it!

**Comment by m-mohr** [comment]
Thanks, done.

**Comment by rouault** [comment]
I should also note that this repo has been done like a "5-minute" (actually a bit more) exercice to demonstrate the equivalence between PROJJSON and WKT2, but I'm not aware of any serious use of it. I'd note that the WKT1 output it generates is highly impractical, as  most WKT1 readers in the wild would likely have troubles using the most recent EPSG datum names, projection methods, projection parameters, etc. True interoperability lies in the ability to understand what is inside double quoted strings, and not just reading/writing the WKT grammar itself. CRS business is hard :-)

**Comment by m-mohr** [comment]
Thanks for the heads up. I'll experiment a bit with how well I can use provided PROJJSON obvjects in the JS ecosystem which for now only supports WKT1 and proj strings, unfortunately...
